# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json
---
printWidth: 120
proseWrap: always
tabWidth: 4
useTabs: false
overrides:
  - files:
      - '*.json'
      - '*.md'
      - '*.yaml'
      - '*.yml'
    options:
      tabWidth: 2
