// Code generated by bitmask; DO NOT EDIT.

package usage

import (
	"fmt"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (f *Flags) Set(mask Flags, value bool) {
	if value {
		*f |= mask
	} else {
		*f &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (f Flags) Has(mask Flags) bool {
	return f&mask == mask
}

// String returns the textual representation of Flags.
func (f Flags) String() string {
	switch f {
	case UsageNone:
		return "Unused"
	}

	txt, err := bitmask.FormatText(uint64(f), _FlagsNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Flags: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (f Flags) MarshalText() ([]byte, error) {
	return f.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (f Flags) AppendText(buf []byte) ([]byte, error) {
	switch f {
	case UsageNone:
		return append(buf, "Unused"...), nil
	}

	return bitmask.AppendText(buf, uint64(f), _FlagsNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (f *Flags) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _FlagsParseName)
	if err != nil {
		return fmt.Errorf("Flags: %w", err)
	}

	*f = Flags(val) // #nosec G115 -- validated during generation.

	return nil
}

var _FlagsNames = [...]string{
	"Used",
	"TypeChange",
	"UntypedNil",
}

// _FlagsParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _FlagsParseName(name string) (uint64, bool) {
	switch name {
	case "Unused":
		return uint64(UsageNone), true
	case "Used":
		return uint64(UsageUsed), true
	case "TypeChange":
		return uint64(UsageTypeChange), true
	case "UntypedNil":
		return uint64(UsageUntypedNil), true
	default:
		return 0, false
	}
}
