// Code generated by bitmask; DO NOT EDIT.

package engine

import (
	"fmt"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (s *SafetyTiers) Set(mask SafetyTiers, value bool) {
	if value {
		*s |= mask
	} else {
		*s &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (s SafetyTiers) Has(mask SafetyTiers) bool {
	return s&mask == mask
}

// String returns the textual representation of SafetyTiers.
func (s SafetyTiers) String() string {
	switch s {
	case None:
		return "none"
	}

	txt, err := bitmask.FormatText(uint64(s), _SafetyTiersNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "SafetyTiers: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (s SafetyTiers) MarshalText() ([]byte, error) {
	return s.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (s SafetyTiers) AppendText(buf []byte) ([]byte, error) {
	switch s {
	case None:
		return append(buf, "none"...), nil
	}

	return bitmask.AppendText(buf, uint64(s), _SafetyTiersNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (s *SafetyTiers) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _SafetyTiersParseName)
	if err != nil {
		return fmt.Errorf("SafetyTiers: %w", err)
	}

	*s = SafetyTiers(val) // #nosec G115 -- validated during generation.

	return nil
}

var _SafetyTiersNames = [...]string{
	"safe",
	"unsafe",
	"breaking",
}

// _SafetyTiersParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _SafetyTiersParseName(name string) (uint64, bool) {
	switch name {
	case "none":
		return uint64(None), true
	case "safe":
		return uint64(Safe), true
	case "unsafe":
		return uint64(Unsafe), true
	case "breaking":
		return uint64(Breaking), true
	default:
		return 0, false
	}
}

// MarshalJSON implements [encoding/json.Marshaler]. It emits a JSON array of bit names
// in ascending bit position order; aliases are not used on output. An empty
// mask is rendered as "[]".
func (s SafetyTiers) MarshalJSON() ([]byte, error) {
	data, err := bitmask.MarshalJSON(uint64(s), _SafetyTiersNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return nil, fmt.Errorf("SafetyTiers: %w", err)
	}

	return data, nil
}

// UnmarshalJSON implements [encoding/json.Unmarshaler]. It accepts:
//   - string: parsed via [SafetyTiers.UnmarshalText] (comma- or whitespace-separated names).
//   - array of strings: each element resolved by name (bit names or aliases).
func (s *SafetyTiers) UnmarshalJSON(data []byte) error {
	val, err := bitmask.UnmarshalJSON(data, _SafetyTiersParseName, 0)
	if err != nil {
		return fmt.Errorf("SafetyTiers: %w", err)
	}

	*s = SafetyTiers(val) // #nosec G115 -- validated during generation.

	return nil
}
