// Code generated by bitmask; DO NOT EDIT.

//go:build go1.27 && goexperiment.jsonv2

package engine

import (
	"encoding/json/jsontext"
	"fmt"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// MarshalJSONTo implements [encoding/json/v2.MarshalerTo]. It emits a JSON array of bit names
// in ascending bit position order; aliases are not used on output. An empty
// mask is rendered as "[]".
func (s SafetyTiers) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := bitmask.MarshalJSONTo(enc, uint64(s), _SafetyTiersNames[:]); err != nil { // #nosec G115 -- validated during generation.
		return fmt.Errorf("SafetyTiers: %w", err)
	}

	return nil
}

// UnmarshalJSONFrom implements [encoding/json/v2.UnmarshalerFrom]. It accepts:
//   - string: parsed via [SafetyTiers.UnmarshalText] (comma- or whitespace-separated names).
//   - array of strings: each element resolved by name (bit names or aliases).
func (s *SafetyTiers) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	val, err := bitmask.UnmarshalJSONFrom(dec, _SafetyTiersParseName, 0)
	if err != nil {
		return fmt.Errorf("SafetyTiers: %w", err)
	}

	*s = SafetyTiers(val) // #nosec G115 -- validated during generation.

	return nil
}
