// Code generated by "stringer -type MoveStatus -linecomment"; DO NOT EDIT.

package analyze

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MoveAllowed-0]
	_ = x[MoveBlockedInitConflict-1]
	_ = x[MoveBlockedTypeIncompatible-2]
	_ = x[MoveBlockedGenerated-3]
	_ = x[MoveBlockedDeclared-4]
	_ = x[MoveBlockedShadowed-5]
	_ = x[MoveBlockedTypeChange-6]
	_ = x[MoveBlockedStatements-7]
}

const _MoveStatus_name = "movinitypgendecshwtchxst"

var _MoveStatus_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24}

func (i MoveStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MoveStatus_index)-1 {
		return "MoveStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MoveStatus_name[_MoveStatus_index[idx]:_MoveStatus_index[idx+1]]
}
