// Code generated by bitmask; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (a *Analyzers) Set(mask Analyzers, value bool) {
	if value {
		*a |= mask
	} else {
		*a &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (a Analyzers) Has(mask Analyzers) bool {
	return a&mask == mask
}

// String returns the textual representation of Analyzers.
func (a Analyzers) String() string {
	txt, err := bitmask.FormatText(uint64(a), _AnalyzersNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Analyzers: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (a Analyzers) MarshalText() ([]byte, error) {
	return a.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (a Analyzers) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(a), _AnalyzersNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (a *Analyzers) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _AnalyzersParseName)
	if err != nil {
		return fmt.Errorf("Analyzers: %w", err)
	}

	*a = Analyzers(val) // #nosec G115 -- validated during generation.

	return nil
}

var _AnalyzersNames = [...]string{
	"scope",
	"shadow",
	"nested-assign",
}

// _AnalyzersParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _AnalyzersParseName(name string) (uint64, bool) {
	switch name {
	case "scope":
		return uint64(ScopeAnalyzer), true
	case "shadow":
		return uint64(ShadowAnalyzer), true
	case "nested-assign":
		return uint64(NestedAssignAnalyzer), true
	default:
		return 0, false
	}
}

// BoolFlag returns a boolean [flag.Value] for a.
//
// Use it with
//
//	var a Analyzers
//	flag.Var(a.BoolFlag(ScopeAnalyzer), "name", "usage")
func (a *Analyzers) BoolFlag(mask Analyzers) AnalyzersBoolFlag {
	return AnalyzersBoolFlag{value: a, mask: mask}
}

// AnalyzersBoolFlag implements [flag.Value] to bind a Analyzers configuration to a specific flag for command-line parsing.
type AnalyzersBoolFlag struct {
	value *Analyzers
	mask  Analyzers
}

// String implements [flag.Value].
func (v AnalyzersBoolFlag) String() string {
	return strconv.FormatBool(v.value != nil && v.value.Has(v.mask))
}

// Set implements [flag.Value].
func (v AnalyzersBoolFlag) Set(s string) error {
	value, err := strconv.ParseBool(s)
	if err != nil {
		return err
	}

	v.value.Set(v.mask, value)

	return nil
}

// IsBoolFlag makes `-name` equivalent to `-name=true`.
func (AnalyzersBoolFlag) IsBoolFlag() bool { return true }
