// Code generated by bitmask; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (b *Behaviors) Set(mask Behaviors, value bool) {
	if value {
		*b |= mask
	} else {
		*b &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (b Behaviors) Has(mask Behaviors) bool {
	return b&mask == mask
}

// String returns the textual representation of Behaviors.
func (b Behaviors) String() string {
	txt, err := bitmask.FormatText(uint64(b), _BehaviorsNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Behaviors: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (b Behaviors) MarshalText() ([]byte, error) {
	return b.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (b Behaviors) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(b), _BehaviorsNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (b *Behaviors) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _BehaviorsParseName)
	if err != nil {
		return fmt.Errorf("Behaviors: %w", err)
	}

	*b = Behaviors(val) // #nosec G115 -- validated during generation.

	return nil
}

var _BehaviorsNames = [...]string{
	"generated",
	"first-only",
	"combine",
	"rename",
}

// _BehaviorsParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _BehaviorsParseName(name string) (uint64, bool) {
	switch name {
	case "generated":
		return uint64(IncludeGenerated), true
	case "first-only":
		return uint64(FirstUseOnly), true
	case "combine":
		return uint64(CombineDeclarations), true
	case "rename":
		return uint64(RenameVariables), true
	default:
		return 0, false
	}
}

// BoolFlag returns a boolean [flag.Value] for b.
//
// Use it with
//
//	var b Behaviors
//	flag.Var(b.BoolFlag(IncludeGenerated), "name", "usage")
func (b *Behaviors) BoolFlag(mask Behaviors) BehaviorsBoolFlag {
	return BehaviorsBoolFlag{value: b, mask: mask}
}

// BehaviorsBoolFlag implements [flag.Value] to bind a Behaviors configuration to a specific flag for command-line parsing.
type BehaviorsBoolFlag struct {
	value *Behaviors
	mask  Behaviors
}

// String implements [flag.Value].
func (v BehaviorsBoolFlag) String() string {
	return strconv.FormatBool(v.value != nil && v.value.Has(v.mask))
}

// Set implements [flag.Value].
func (v BehaviorsBoolFlag) Set(s string) error {
	value, err := strconv.ParseBool(s)
	if err != nil {
		return err
	}

	v.value.Set(v.mask, value)

	return nil
}

// IsBoolFlag makes `-name` equivalent to `-name=true`.
func (BehaviorsBoolFlag) IsBoolFlag() bool { return true }
