// Code generated by bitmask; DO NOT EDIT.

package config

import (
	"fmt"
	"strconv"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (s *Safety) Set(mask Safety, value bool) {
	if value {
		*s |= mask
	} else {
		*s &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (s Safety) Has(mask Safety) bool {
	return s&mask == mask
}

// String returns the textual representation of Safety.
func (s Safety) String() string {
	switch s {
	case All:
		return "all"
	case Nothing:
		return "none"
	}

	txt, err := bitmask.FormatText(uint64(s), _SafetyNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Safety: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (s Safety) MarshalText() ([]byte, error) {
	return s.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (s Safety) AppendText(buf []byte) ([]byte, error) {
	switch s {
	case All:
		return append(buf, "all"...), nil
	case Nothing:
		return append(buf, "none"...), nil
	}

	return bitmask.AppendText(buf, uint64(s), _SafetyNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (s *Safety) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _SafetyParseName)
	if err != nil {
		return fmt.Errorf("Safety: %w", err)
	}

	*s = Safety(val) // #nosec G115 -- validated during generation.

	return nil
}

var _SafetyNames = [...]string{
	"safe",
	"unsafe",
	"breaking",
}

// _SafetyParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _SafetyParseName(name string) (uint64, bool) {
	switch name {
	case "all":
		return uint64(All), true
	case "none":
		return uint64(Nothing), true
	case "safe":
		return uint64(Safe), true
	case "unsafe":
		return uint64(Unsafe), true
	case "breaking":
		return uint64(Breaking), true
	default:
		return 0, false
	}
}

// BoolFlag returns a boolean [flag.Value] for s.
//
// Use it with
//
//	var s Safety
//	flag.Var(s.BoolFlag(Safe), "name", "usage")
func (s *Safety) BoolFlag(mask Safety) SafetyBoolFlag {
	return SafetyBoolFlag{value: s, mask: mask}
}

// SafetyBoolFlag implements [flag.Value] to bind a Safety configuration to a specific flag for command-line parsing.
type SafetyBoolFlag struct {
	value *Safety
	mask  Safety
}

// String implements [flag.Value].
func (v SafetyBoolFlag) String() string {
	return strconv.FormatBool(v.value != nil && v.value.Has(v.mask))
}

// Set implements [flag.Value].
func (v SafetyBoolFlag) Set(s string) error {
	value, err := strconv.ParseBool(s)
	if err != nil {
		return err
	}

	v.value.Set(v.mask, value)

	return nil
}

// IsBoolFlag makes `-name` equivalent to `-name=true`.
func (SafetyBoolFlag) IsBoolFlag() bool { return true }
