---
when:
  - event: push
    branch: [main, dev]

matrix:
  GO_VERSION:
    - "tip"

steps:
  - name: test
    image: golang:${GO_VERSION}
    environment:
      GOTOOLCHAIN: local
    commands:
      - go telemetry on
      - echo "🤖 Run Vulnerability Scanner:"
      - go run golang.org/x/vuln/cmd/govulncheck@master ./...
      - echo "⬆️ Update to latest dependency versions:"
      - find . -name go.mod -execdir go get -u ./... \; -execdir go mod tidy \;
      - echo "🔨 Test on $(go version):"
      - go test ./...
