---
when:
  - event: push
    branch: [main, dev]

matrix:
  GO_VERSION:
    - "1.26rc2"
    - "1.25.6"
    - "1.24.12"

steps:
  - name: test
    image: golang:${GO_VERSION}
    environment:
      GOTOOLCHAIN: local
    commands:
      - go telemetry on
      - go mod download && (cd ./internal/reachability/tracker/testdata && go mod download)
      - echo "🔨 Testing on $(go version):"
      - go test ./...
