---
when:
  - event: push
    branch: [main, dev]

matrix:
  GO_VERSION:
    - "1.26rc1"
    - "1.25.5"
    - "1.24.11"

steps:
  - name: test
    image: golang:${GO_VERSION}
    environment:
      GOTOOLCHAIN: local
    commands:
      - go telemetry on
      - echo "🔨 Testing on $(go version):"
      - go test ./...
