// Code generated by bitmask; DO NOT EDIT.

package bitmask

import (
	"fmt"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (b *Bitmask) Set(mask Bitmask, value bool) {
	if value {
		*b |= mask
	} else {
		*b &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (b Bitmask) Has(mask Bitmask) bool {
	return b&mask == mask
}

// String returns the textual representation of Bitmask.
func (b Bitmask) String() string {
	switch b {
	case All:
		return "all"
	case None:
		return "zero"
	}

	txt, err := bitmask.FormatText(uint64(b), _BitmaskNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Bitmask: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (b Bitmask) MarshalText() ([]byte, error) {
	return b.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (b Bitmask) AppendText(buf []byte) ([]byte, error) {
	switch b {
	case All:
		return append(buf, "all"...), nil
	case None:
		return append(buf, "zero"...), nil
	}

	return bitmask.AppendText(buf, uint64(b), _BitmaskNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (b *Bitmask) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _BitmaskParseName)
	if err != nil {
		return fmt.Errorf("Bitmask: %w", err)
	}

	*b = Bitmask(val) // #nosec G115 -- validated during generation.

	return nil
}

var _BitmaskNames = [...]string{
	"one",
	"two",
	"three",
}

// _BitmaskParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _BitmaskParseName(name string) (uint64, bool) {
	switch name {
	case "all":
		return uint64(All), true
	case "zero":
		return uint64(None), true
	case "one":
		return uint64(One), true
	case "two":
		return uint64(Two), true
	case "three":
		return uint64(Three), true
	default:
		return 0, false
	}
}

// MarshalJSON implements [encoding/json.Marshaler]. It emits a JSON array of bit names
// in ascending bit position order; aliases are not used on output. An empty
// mask is rendered as "[]".
func (b Bitmask) MarshalJSON() ([]byte, error) {
	data, err := bitmask.MarshalJSON(uint64(b), _BitmaskNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return nil, fmt.Errorf("Bitmask: %w", err)
	}

	return data, nil
}

// UnmarshalJSON implements [encoding/json.Unmarshaler]. It accepts:
//   - bool: true sets [All]; false Bitmask(0).
//   - string: parsed via [Bitmask.UnmarshalText] (comma- or whitespace-separated names).
//   - array of strings: each element resolved by name (bit names or aliases).
func (b *Bitmask) UnmarshalJSON(data []byte) error {
	val, err := bitmask.UnmarshalJSON(data, _BitmaskParseName, uint64(All))
	if err != nil {
		return fmt.Errorf("Bitmask: %w", err)
	}

	*b = Bitmask(val) // #nosec G115 -- validated during generation.

	return nil
}
