// Code generated by bitmask; DO NOT EDIT.

//go:build go1.27 && goexperiment.jsonv2

package bitmask_test

import (
	"encoding/json/jsontext"
	"fmt"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// MarshalJSONTo implements [encoding/json/v2.MarshalerTo]. It emits a JSON array of bit names
// in ascending bit position order; aliases are not used on output. An empty
// mask is rendered as "[]".
func (f Flag) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := bitmask.MarshalJSONTo(enc, uint64(f), _FlagNames[:]); err != nil { // #nosec G115 -- validated during generation.
		return fmt.Errorf("Flag: %w", err)
	}

	return nil
}

// UnmarshalJSONFrom implements [encoding/json/v2.UnmarshalerFrom]. It accepts:
//   - string: parsed via [Flag.UnmarshalText] (comma- or whitespace-separated names).
//   - array of strings: each element resolved by name (bit names or aliases).
func (f *Flag) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	val, err := bitmask.UnmarshalJSONFrom(dec, _FlagParseName, 0)
	if err != nil {
		return fmt.Errorf("Flag: %w", err)
	}

	*f = Flag(val) // #nosec G115 -- validated during generation.

	return nil
}
