// Code generated by bitmask; DO NOT EDIT.

package bitmask_test

import (
	"fmt"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (f *Flag) Set(mask Flag, value bool) {
	if value {
		*f |= mask
	} else {
		*f &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (f Flag) Has(mask Flag) bool {
	return f&mask == mask
}

// String returns the textual representation of Flag.
func (f Flag) String() string {
	txt, err := bitmask.FormatText(uint64(f), _FlagNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Flag: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (f Flag) MarshalText() ([]byte, error) {
	return f.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (f Flag) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(f), _FlagNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (f *Flag) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _FlagParseName)
	if err != nil {
		return fmt.Errorf("Flag: %w", err)
	}

	*f = Flag(val) // #nosec G115 -- validated during generation.

	return nil
}

var _FlagNames = [...]string{
	"read",
	"write",
}

// _FlagParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _FlagParseName(name string) (uint64, bool) {
	switch name {
	case "read":
		return uint64(FlagRead), true
	case "write":
		return uint64(FlagWrite), true
	default:
		return 0, false
	}
}

// MarshalJSON implements [encoding/json.Marshaler]. It emits a JSON array of bit names
// in ascending bit position order; aliases are not used on output. An empty
// mask is rendered as "[]".
func (f Flag) MarshalJSON() ([]byte, error) {
	data, err := bitmask.MarshalJSON(uint64(f), _FlagNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return nil, fmt.Errorf("Flag: %w", err)
	}

	return data, nil
}

// UnmarshalJSON implements [encoding/json.Unmarshaler]. It accepts:
//   - string: parsed via [Flag.UnmarshalText] (comma- or whitespace-separated names).
//   - array of strings: each element resolved by name (bit names or aliases).
func (f *Flag) UnmarshalJSON(data []byte) error {
	val, err := bitmask.UnmarshalJSON(data, _FlagParseName, 0)
	if err != nil {
		return fmt.Errorf("Flag: %w", err)
	}

	*f = Flag(val) // #nosec G115 -- validated during generation.

	return nil
}
