// Code generated by bitmask; DO NOT EDIT.

package bitmask

import (
	"fmt"
	"strconv"

	"fillmore-labs.com/scopeguard/internal/bitmask"
)

// Set adjusts the bitmask by enabling or disabling the specified mask.
func (m *Mode) Set(mask Mode, value bool) {
	if value {
		*m |= mask
	} else {
		*m &^= mask
	}
}

// Has reports whether every bit in mask is set on the receiver. With a multi-bit mask
// it is a strict containment check; calling Has(0) always returns true.
func (m Mode) Has(mask Mode) bool {
	return m&mask == mask
}

// String returns the textual representation of Mode.
func (m Mode) String() string {
	txt, err := bitmask.FormatText(uint64(m), _ModeNames[:]) // #nosec G115 -- validated during generation.
	if err != nil {
		return "Mode: " + err.Error()
	}

	return txt
}

// MarshalText implements [encoding.TextMarshaler].
func (m Mode) MarshalText() ([]byte, error) {
	return m.AppendText(nil)
}

// AppendText implements [encoding.TextAppender].
func (m Mode) AppendText(buf []byte) ([]byte, error) {
	return bitmask.AppendText(buf, uint64(m), _ModeNames[:]) // #nosec G115 -- validated during generation.
}

// UnmarshalText implements [encoding.TextUnmarshaler].
// It parses a comma- or whitespace-separated list of names.
func (m *Mode) UnmarshalText(text []byte) error {
	val, err := bitmask.UnmarshalText(text, _ModeParseName)
	if err != nil {
		return fmt.Errorf("Mode: %w", err)
	}

	*m = Mode(val) // #nosec G115 -- validated during generation.

	return nil
}

var _ModeNames = [...]string{
	"read",
	"write",
}

// _ModeParseName resolves "name" to its bit value, reporting
// whether it was recognized.
func _ModeParseName(name string) (uint64, bool) {
	switch name {
	case "read":
		return uint64(ModeRead), true
	case "write":
		return uint64(ModeWrite), true
	default:
		return 0, false
	}
}

// BoolFlag returns a boolean [flag.Value] for m.
//
// Use it with
//
//	var m Mode
//	flag.Var(m.BoolFlag(ModeRead), "name", "usage")
func (m *Mode) BoolFlag(mask Mode) ModeBoolFlag {
	return ModeBoolFlag{value: m, mask: mask}
}

// ModeBoolFlag implements [flag.Value] to bind a Mode configuration to a specific flag for command-line parsing.
type ModeBoolFlag struct {
	value *Mode
	mask  Mode
}

// String implements [flag.Value].
func (v ModeBoolFlag) String() string {
	return strconv.FormatBool(v.value != nil && v.value.Has(v.mask))
}

// Set implements [flag.Value].
func (v ModeBoolFlag) Set(s string) error {
	value, err := strconv.ParseBool(s)
	if err != nil {
		return err
	}

	v.value.Set(v.mask, value)

	return nil
}

// IsBoolFlag makes `-name` equivalent to `-name=true`.
func (ModeBoolFlag) IsBoolFlag() bool { return true }
